name: Rename Folder by Path

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'
      folder_path:
        description: 'Full relative path to folder to rename (e.g. Angular/Folder/My_Folder'
        required: true
      new_folder_name:
        description: 'New folder name'
        required: true

jobs:
  rename_folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Rename folder
        run: |
          folder_path="${{ github.event.inputs.folder_path }}"
          new_name="${{ github.event.inputs.new_folder_name }}"

          # Extract parent directory path
          parent_dir=$(dirname "$folder_path")

          echo "Renaming folder '$folder_path' to '$parent_dir/$new_name'"

          # Check if folder exists
          if [ -d "$folder_path" ]; then
            mv "$folder_path" "$parent_dir/$new_name"
          else
            echo "Error: Folder '$folder_path' does not exist!"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Rename folder '${{ github.event.inputs.folder_path }}' to '${{ github.event.inputs.new_folder_name }}'"
          git push origin ${{ github.event.inputs.branch }}
        continue-on-error: true
