name: Rename Folders

on:
  workflow_dispatch: # manually trigger

jobs:
  rename-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Rename folders recursively
        run: |
          # Define old and new folder names here
          OLD_NAME="oldfoldername"
          NEW_NAME="newfoldername"

          # Find and rename directories matching OLD_NAME recursively
          find . -type d -name "$OLD_NAME" | while read -r dir; do
            # Rename folder
            git mv "$dir" "$(dirname "$dir")/$NEW_NAME"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Rename folders from $OLD_NAME to $NEW_NAME"
          git push
