name: Rename Folders

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'
      old_folder_name:
        description: 'Folder name to rename'
        required: true
      new_folder_name:
        description: 'New folder name'
        required: true

jobs:
  rename_folders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Find and rename folders recursively
        run: |
          old="${{ github.event.inputs.old_folder_name }}"
          new="${{ github.event.inputs.new_folder_name }}"
          
          # Find all directories named exactly $old (case sensitive)
          find . -type d -name "$old" | while read -r dir; do
            # Get the parent directory
            parent=$(dirname "$dir")
            echo "Renaming $dir to $parent/$new"
            mv "$dir" "$parent/$new"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Rename folder '${{ github.event.inputs.old_folder_name }}' to '${{ github.event.inputs.new_folder_name }}'"
          git push origin ${{ github.event.inputs.branch }}
        # If no changes, skip failure
        continue-on-error: true
